### ISSUE TITLE
Agregar el metodo a su pagina correspondiente

### ISSUE THREAD

**Issue by FabrizioOtranto** [Makangel/nuevo-proyecto-template#1]
https://github.com/Makangel/nuevo-proyecto-template/blob/b852cb06074d870ad2466fd724a4c893f589f7ec/cypress/e2e/tests.cy.js#L43

**Comment by Makangel** [comment]
Solucionado en ultimo deploy llamado 'correccion 1'.
cambios realizados:
productsPage.js: agregue el metodo
 gotoShoppingCart(){
    cy.xpath("//button[contains(text(),'Go to shopping cart')]").click();
  };

tests.cy.js: reemplaze la linea 43 y ejecute el metodo desde la clase.
  productsPage.goToShoppingCart();
