### ISSUE TITLE
La asercion debe ser en el test

### ISSUE THREAD

**Issue by FabrizioOtranto** [Makangel/nuevo-proyecto-template#2]
Debes retornar el elemento y luego hacer la asercion en el test. Debes usar ('have.text') en vez de ('exist')

Chequear clase 6

https://github.com/Makangel/nuevo-proyecto-template/blob/b852cb06074d870ad2466fd724a4c893f589f7ec/cypress/support/pages/shoppingCartPage.js#L7

**Comment by Makangel** [comment]
Solucionado en ultimo deploy llamado 'correccion 1'.
cambios realizados:
shoppingCartPage.js: agregue el metodo para que retorne el elemento con el nombre del producto
verificarNombreProducto(producto){
    return cy.xpath(`//p[contains(text(),"${producto}")]`);
}

tests.cy.js: reemplaze la linea 45 y 48. Ejecute el método desde la clase y realice la asercion en el test
shoppingCartPage.verificarNombreProducto(productsData.WhitePants.name).should("have.text",producto);
shoppingCartPage.verificarNombreProducto(productsData.RedCap.name).should("have.text",producto);
