### ISSUE TITLE
Crear metodo en la pagina correspondiente

### ISSUE THREAD

**Issue by FabrizioOtranto** [Makangel/nuevo-proyecto-template#4]
https://github.com/Makangel/nuevo-proyecto-template/blob/b852cb06074d870ad2466fd724a4c893f589f7ec/cypress/e2e/tests.cy.js#L51

**Comment by Makangel** [comment]
Solucionado en ultimo deploy llamado 'correccion 1'.
cambios realizados:
shoppingCartPage.js: agregue el metodo
clickShowTotalPrice(){
    cy.xpath("//button[contains(text(),'Show total price')]").click();
};

tests.cy.js: reemplaze la linea 51 y ejecute el metodo desde la clase.
  shoppingCartPage.clickShowTotalPrice();
