### ISSUE TITLE
Crear metodo en la pagina correspondiente

### ISSUE THREAD

**Issue by FabrizioOtranto** [Makangel/nuevo-proyecto-template#5]
https://github.com/Makangel/nuevo-proyecto-template/blob/b852cb06074d870ad2466fd724a4c893f589f7ec/cypress/e2e/tests.cy.js#L53

**Comment by Makangel** [comment]
Solucionado en ultimo deploy llamado 'correccion 1'.
cambios realizados:
shoppingCartPage.js: agregue el metodo y le quite la asercion 'should' porque deberia estar en el test.
verifyTotalPrice(total){
    return cy.contains(total);
};
tests.cy.js: reemplaze la linea 53 y ejecute el método desde la clase y agregue la asercion en el test.
  shoppingCartPage.verifyTotalPrice(auxiliar).should("have.text",auxiliar);
